# NumPy Exercise

In [ ]:
# Make Sure Numpy is imported Correctly imported

try:
    import numpy as np
except ImportError:
    print("Installing Numpy")
    import subprocess
    import sys
    subprocess.check_call([sys.executable, "-m", "pip", "install", "numpy"])
    print("Numpy Installed Sucessfully")
    import numpy as np

### Q1: create 2D-array that contain even numbers between 0-18

In [34]:
np.arange(0, 19, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Q2: Replace the negative values with 0 in random array that has value in range (-6,6)

In [35]:
# init a random array of size 6 ranging between -6 and 6
random_arr = np.random.randint(low=-6, high=7, size=(6))

# Orignal Array
print("Orignal Array :")
print(random_arr, "\n\n")

# Replace Negative With 0
random_arr[random_arr < 0] = 0

# Modified Array
print("Modified Array :")
print(random_arr)

Orignal Array :
[-2  2  6 -5  2  0] 


Modified Array :
[0 2 6 0 2 0]


### Q3: How to compute the following expression?

$$(A + B) \times \left( \frac{-A}{2} \right)$$

Where `A` and `B` are NumPy random arrays.

In [36]:
# Init Arrays A and B

A = np.random.randint(low=0, high=11, size=(6))
B = np.random.randint(low=0, high=11, size=(6))

# Print Arrays
print("Arrays A and B")
print("A : ", A)
print("B : ", B)

# Calulate Expression
R = (A + B) * (A / -2)

# Print Result
print("Result : ", R)

Arrays A and B
A :  [4 8 2 0 9 0]
B :  [6 0 5 8 5 6]
Result :  [-20. -32.  -7.  -0. -63.  -0.]


### Q4: How to concatenate two arrays horizontally?

In [47]:
# Init Arrays X and Y

X = np.random.randint(low=0, high=11, size=(6))
Y = np.random.randint(low=0, high=11, size=(6))

# Print Arrays
print("Arrays X and Y")
print("X : ", X)
print("Y : ", Y)

# 1st Way : Use Hstack
# concat horizontally
h = np.hstack([X, Y])

print("\nFirst Way : Use np.hstack()")
print("H : ", h)

# 2nd Way : Use np.concatenate()
c = np.concatenate((X, Y))

print("\nSeocnd Way : Use np.concatenate()")
print("C : ", c)

Arrays X and Y
X :  [8 7 1 2 5 1]
Y :  [2 3 8 6 5 8]

First Way : Use np.hstack()
H :  [8 7 1 2 5 1 2 3 8 6 5 8]

Seocnd Way : Use np.concatenate()
C :  [8 7 1 2 5 1 2 3 8 6 5 8]


### Q5: Create a array vector of size 3x3 and sort values in Its columns

In [56]:
# Init Matrix 3x3
matrix = np.random.randint(low=0, high=11, size=(3,3))

# Matrix Before Sort
print("matrix Before Sort: ")
print(matrix)

# Sort According To Columns "axis = 0"
x = np.sort(matrix, axis=0)

print("\nmatrix After Sort: ")
print(x)

matrix Before Sort: 
[[4 3 1]
 [6 7 8]
 [2 9 0]]

matrix After Sort: 
[[2 3 0]
 [4 7 1]
 [6 9 8]]
